# Academic Pages Configuration
title: Junteng Liu
description: First-year PhD candidate at HKUST NLP Group, researching NLP and Machine Learning.
author: Junteng Liu
email: jliugi@connect.ust.hk
avatar: 
github: Vicent0205
google_scholar: https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate
twitter: junteng88716710

# Site settings
baseurl: "" 
url: ""

# Build settings
markdown: kramdown
permalink: /:title/
